### PR TITLE
added os.path.expanduser to filenames

### PR DESCRIPTION
**Pull request by robertvanbregt**
Fix for #37.

### CODE REVIEW

**Comment by bram85** [comment]
As explained in issue #37, this fix is not complete. Ideally it should be fixed in the `Config` class.

**Comment by robertvanbregt** [comment]
Applied patch to Config.py instead of Main.py

**Comment by mruwek** [comment]
Can You squash your commits, so we don't unnecessarily pollute git history?

Try this:
```
git rebase -i b6796c1b00c9e37e5bcc31f54fddd8cda7931763
```

Then change `pick` to `squash` for: 0fde5b6 and 0fde5b6, edit final-commit message and after successful rebase do:

```
git push --force origin fix/issue37
```

**Comment by robertvanbregt** [comment]
At your service. I'm a git newbie / n00b but learning rapidly. Sorry for the inconvenience.

**Comment by bram85** [comment]
Thanks for the fix.

**Pull request merged**
