### PR TITLE
Append command: process due dates, start (threshold) dates, and depedancies

### PR DESCRIPTION
**Pull request by MinchinWeb**
I have a habit of appending due dates to existing items on my todo list. However, relative dates weren't being processed. This fixes that.

As well, adding project dependencies via `append` now works as well.

Includes a test case as well, and passes the existing test suite.

### CODE REVIEW

**Comment by MinchinWeb** [comment]
c.f. #129

**Comment by bram85** [comment]
I tend to choose the implementation of #129, which introduces a `WriteCommand` that abstracts away the common functionality for `add` and `append`. I like that better than having `TodoList` handle that.

It stays a bit unfortunate that this functionality has been implemented twice, blaming mostly myself for lingering these PRs around for too long.

**Comment by bram85** [comment]
Merged #129

**Comment by MinchinWeb** [comment]
@bram85 : I'm glad you used what you felt was the better code. I had tried to abstract out the common parts between `add` and `append` and couldn't get it to work myself. I'll keep little updates coming as time permits.

**Pull request closed without merging**
