### PR TITLE
configurable focus and marked background colors

### PR DESCRIPTION
**Pull request by colinsullivan**
This patch allows the background colors of focused and marked todos to be configured using new configuration options.

With these values:

```
[colorscheme]
focus_background_color = 8
marked_background_color = 16
```

My terminal displays this:

screen shot 2016-11-21 at 11 45 54 am

Defaults are working.

Addresses #140

### CODE REVIEW

**Comment by bram85** [comment]
First of all, thanks for your patch!

I see that the test coverage degraded somewhat, you could fix that by adding the new configuration items to [test/data/ColorsTest5.conf](https://github.com/bram85/topydo/blob/master/test/data/ColorsTest5.conf).

Moreover, when all is in place, please squash the commit history to a single commit to keep the log clean.

**Comment by colinsullivan** [comment]
@bram85 I added config items you suggested, seems like a similar result?

**Comment by bram85** [comment]
I noticed, I'm fixing it up here locally, I do expect to commit and merge by tomorrow. There's still some tests to be added to test/test_{config,colors}.py to cover all code.

**Comment by bram85** [comment]
I added the tests and merged with a [new commit](https://github.com/bram85/topydo/commit/162cc7769505ea455d8f4dac426afeaaebf71713) (also squashed the separate commits).

**Pull request closed without merging**
